### PR TITLE
(FAILING) Beta 5 update

### LINKED ISSUE #434: Update to beta.3
Blocked by https://github.com/angular/angular/issues/6887

### PR DESCRIPTION
**Pull request by jesperronn**
#Updating to tonights release of angular2.beta.5

see https://github.com/angular/angular/blob/master/CHANGELOG.md

Should eventually fix #434 

-------------
# Problem number 4:

Travis/Appveyor build. The error seems to be that angular2.beta.5 postinstall step installs the peer typings es6-shim, etc. This problem I solved locally, but it may require special handling. That is exactly the problem which is fixed in angular https://github.com/angular/angular/pull/7003, as is scheduled to be updated very shortly.

-------------
# Problem number 3 (fixed):

Note this problem is fixed with commit de796fcb3b5a197bae79fc388c14b37344b3b33d

No tests run!

`karma.conf.js` loading tests also needs the hack I did below until `angular2.beta.6` is out. 

Question: How to rewrite paths in `karma.conf.js`?

-------------
# Problem number 2 (fixed) :

Note this problem is fixed in commit 9fa6686556b0f1458e9bcfccdc5349c1f23ea3ab

RXJS paths have changed.
This results in tests nut running, since karma doesnt serve the correct files longer.

It turns out there are two issues, that the Angular team will fix within a day and plan a release after
https://github.com/angular/angular/pull/7002 and https://github.com/angular/angular/pull/7003 has landed.

See https://github.com/angular/angular/issues/7001 for details.

Example run:

```
11 02 2016 08:55:03.518:WARN [web-server]: 404: /base/node_modules/rxjs/observable/fromPromise.js
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: Error{stack: undefined, line: 741, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c'}
11 02 2016 08:55:03.730:WARN [web-server]: 404: /base/node_modules/rxjs/observable/fromPromise.js
11 02 2016 08:55:03.934:WARN [web-server]: 404: /base/node_modules/rxjs/observable/fromPromise.js
ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/rxjs/observable/fromPromise.js
    at error (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c:1021:16)
    at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c:1042:13)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?87bbeaae4d01ebf513e1bbea41a0e13dbad92eb4:1217:24)
    at XMLHttpRequest.zoneBoundFn (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?87bbeaae4d01ebf513e1bbea41a0e13dbad92eb4:1194:26)'
11 02 2016 08:55:04.077:WARN [web-server]: 404: /base/node_modules/rxjs/observable/fromPromise.js

Finished in 0.29 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

------------

# Problem number 1 (fixed):

Gives me the following error during `npm run postinstall` step. Just posting here in case you can figure out how to fix it. 

Fixed as described below, but see https://github.com/angular/angular/pull/6267 and changelog message https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta5-2016-02-10 (typings change).

```
 $ npm run postinstall

> angular2-seed@0.0.0 postinstall /Users/jesper/src/jesperronn-angular2-seed
> typings install && npm run clean-ng2 && gulp check.versions && gulp postinstall


├── es6-promise
├── xhr2
├── Q (ambient)
├── angular-protractor (ambient)
├── async (ambient)
├── browser-sync (ambient)
├── browserify (ambient)
├── chalk (ambient)
├── chokidar (ambient)
├── del (ambient)
├── es6-shim (ambient)
├── express (ambient)
├── glob (ambient)
├── gulp (ambient)
├── gulp-load-plugins (ambient)
├── gulp-shell (ambient)
├── gulp-util (ambient)
├── jasmine (ambient)
├── micromatch (ambient)
├── mime (ambient)
├── minimatch (ambient)
├── ng2 (ambient)
├── node (ambient)
├── orchestrator (ambient)
├── parse-glob (ambient)
├── run-sequence (ambient)
├── selenium-webdriver (ambient)
├── serve-static (ambient)
├── systemjs (ambient)
├── through2 (ambient)
├── vinyl (ambient)
├── vinyl-source-stream (ambient)
├── yargs (ambient)
└── zone.js (ambient)


> angular2-seed@0.0.0 clean-ng2 /Users/jesper/src/jesperronn-angular2-seed
> rimraf node_modules/angular2/manual_typings node_modules/angular2/typings

[06:53:36] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

typings/main/ambient/es6-collections/es6-collections.d.ts (24,5): Duplicate identifier 'done'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (25,5): Duplicate identifier 'value'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (48,5): Duplicate identifier 'size'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (54,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (68,5): Duplicate identifier 'size'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (74,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (90,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-collections/es6-collections.d.ts (105,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-promise/es6-promise.d.ts (14,15): Duplicate identifier 'Promise'. (2300)
typings/main/ambient/es6-promise/es6-promise.d.ts (45,16): Duplicate identifier 'Promise'. (2300)
typings/main/ambient/es6-promise/es6-promise.d.ts (75,2): An export assignment cannot be used in a module with other exported elements. (2309)
typings/main/ambient/es6-shim/es6-shim.d.ts (11,5): Duplicate identifier 'done'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (12,5): Duplicate identifier 'value'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (477,11): Duplicate identifier 'Promise'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (554,13): Duplicate identifier 'Promise'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (563,5): Duplicate identifier 'size'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (572,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (583,5): Duplicate identifier 'size'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (592,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (607,5): Duplicate identifier 'prototype'. (2300)
typings/main/ambient/es6-shim/es6-shim.d.ts (621,5): Duplicate identifier 'prototype'. (2300)
----------------------------------

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/jesper/.nvm/versions/node/v5.5.0/bin/node" "/usr/local/bin/npm" "run" "postinstall"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `typings install && npm run clean-ng2 && gulp check.versions && gulp postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'typings install && npm run clean-ng2 && gulp check.versions && gulp postinstall'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && npm run clean-ng2 && gulp check.versions && gulp postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesper/src/jesperronn-angular2-seed/npm-debug.log


```

eventually this `Problem number 1` was fixed by removing the `/typings` folder and running a reinstall.

### CODE REVIEW

**Comment by jesperronn** [comment]
There is a note about a breaking change with transitive typings for Angular2.beta.5:

https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

> Transitive typings are no longer included in the distribution.
> 
> If you use `--target=es5`, you will need to add a line somewhere in your application (for example, at the top of the .ts file where you call bootstrap):
> 
> `///<reference path="node_modules/angular2/typings/browser.d.ts"/>`
> (Note that if your file is not in the same directory as node_modules, you'll need to add one or more ../ to the start of that path.)
> 
> If you have unit tests, you need to install typings in your project using http://github.com/typings/typings And install typings such as `jasmine`, `angular-protractor`, or `selenium-webdriver` to satisfy the type-checker.

**Comment by mgechev** [comment]
Good job! I'll take a look at this during the weekend.

**Comment by jesperronn** [comment]
@mgechev Thanks! There is another release fixing beta.5 on its way, see https://github.com/angular/angular/issues/7001#issuecomment-182759753

**Comment by jesperronn** [comment]
Note 'Problem number 4' Only a single problem with CI and typings which is expected to be fixed when https://github.com/angular/angular/pull/7003 lands.

@mgechev the `angular2-hot-loader` also needs a bump in versions, since my commits here temporarily commented out the hot-loader until fixed. (just so that you are aware)

**Comment by mgechev** [comment]
@jesperronn I disabled the hot loader temporary. There are plenty if issues with beta.4 and beta.5 so I'm not planning to merge them in master for now. Most likely I'll tag them once beta.6 is out.

**Comment by antonybudianto** [comment]
no need to hack the rxjs path since angular2-beta.6 revert to rxjs-beta.0 again

**Comment by jesperronn** [comment]
Replaced by #469 since beta.5 was withdrawn from angular project due to the issues described above.

**Pull request closed without merging**
