### PR TITLE
Update to Alpha 41

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by ludohenin** [comment]
Will check that tonight and merge it.

**Comment by NathanWalker** [comment]
If we can figure out https://github.com/mgechev/angular2-seed/pull/153 and why Travis is failing, we may want to opt for that PR... I have changes to match the latest `bind` > `provide`, etc in there :+1:

**Comment by mgechev** [comment]
Okay, lets first merge alpha41 in order to create a tag with it. After that, when we discover what the problem is, we can merge alpha42 and tag.

**Comment by ludohenin** [comment]
There is an issue with the spec files ... working on it update if I succeed.
Travis says it's passing though ...

**Comment by ludohenin** [comment]
I'm stuck with `AsyncTestCompleter`

**Comment by mgechev** [comment]
@ludohenin would you take a look at the PR? I think it is ready to merge, let me know if you find any issues.

**Comment by ludohenin** [comment]
yes, will check that this evening.

**Comment by ludohenin** [comment]
@mgechev Have you changed something ?

**Comment by mgechev** [comment]
I did some changes in the typing defs

**Comment by mgechev** [comment]
Missing `AsyncTestCompleter` // https://github.com/angular/angular/issues/4715

**Comment by ludohenin** [comment]
A work around would be to load `AsyncTestCompleter` from `angular2/testing_internal` but then we get a `No Provider Error` (don't know how to fix this). Seems like there's a binding missing somewhere.

**Comment by ludohenin** [comment]
Component unit test are broken due to [angular/angular#4715](https://github.com/angular/angular/issues/4715).

**Pull request merged**
