### PR TITLE
Update to release beta.17

### PR DESCRIPTION
**Pull request by Shyam-Chen**

### CODE REVIEW

**Comment by JohnCashmore** [comment]
Is node 5 a requirement now?

**Comment by Shyam-Chen** [comment]
@JohnCashmore

**Comment by Shyam-Chen** [comment]
@JohnCashmore `npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants rxjs@5.0.0-beta.6`

**Comment by JohnCashmore** [comment]
My worry would be that node v4 is the LTS version and node 6 is the latest

**Comment by Shyam-Chen** [comment]
@JakePartusch anuglar/angular#8120

**Pull request merged**
