### PR TITLE
Add unit test

### PR DESCRIPTION
**Pull request by ludohenin**

### CODE REVIEW

**Comment by mgechev** [comment]
There are some conflicts. Would you merge it with master locally in order to be able to merge it easier here?

**Comment by ludohenin** [comment]
Yeah sure. My bad :-/

**Comment by ludohenin** [comment]
Done. If you want to have a final look before pushing the green button.

**Comment by mgechev** [comment]
Thanks, I'll merge in a few mins.

**Comment by mgechev** [comment]
Fixes #25

**Pull request merged**
