### PR TITLE
Updated router in app and fixed build

### PR DESCRIPTION
**Pull request by JohnCashmore**
I've updated the app to use the new router, this needs to be checked. The tests have not been updated yet, I've also updated the build so that it works when doing an npm start

### CODE REVIEW

**Comment by JohnCashmore** [comment]
still a WIP

**Comment by NathanWalker** [comment]
I like this best. New router 👍 thx @JohnCashmore

**Comment by mgechev** [comment]
@JohnCashmore anything pending?

**Comment by d3viant0ne** [comment]
@mgechev We going to merge this after you finish tinkering with rc0 & the tag or just scoot on over to rc1?

**Comment by mgechev** [comment]
We can merge rc0, I'll downgrade and tag locally and push only the tag.

**Comment by NathanWalker** [comment]
@mgechev sounds like this PR is clear to merge? @JohnCashmore looks good, is there anything else that you know of to be looked at here?

**Comment by mgechev** [comment]
Specs are not yet updated.

**Pull request merged**
