### PR TITLE
test component that uses Router

### PR DESCRIPTION
**Pull request by larsthorup**
This was inspired by https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/router_link_spec.ts

### CODE REVIEW

**Comment by mgechev** [comment]
Looks great! There's only appveyor failing. Related to this issue I guess https://github.com/mgechev/angular2-seed/issues/244

**Comment by ludohenin** [comment]
From appveyor logs the error is coming from `karma.start` task. Not related to #244

**Comment by larsthorup** [comment]
In a private project, we have experienced AppVeyor / IE being slow to start, and have had success having this in our karma.conf.js: 

    config.browserNoActivityTimeout = 60000;

**Comment by mgechev** [comment]
@larsthorup would you increase the timeout in this PR and see what will be the result of AppVeyor?

**Comment by larsthorup** [comment]
@mgechev Done

**Comment by ludohenin** [comment]
and passing, thanks @larsthorup

**Pull request merged**
