### PR TITLE
chore(deps): support protractor v4

### PR DESCRIPTION
**Pull request by Shyam-Chen**

### CODE REVIEW

**Comment by TheDonDope** [comment]
Protractor v4 has a semantic version number of `^3.0.0` ?

**Comment by Shyam-Chen** [comment]
Should update the definition of `typings`.

**Comment by mgechev** [comment]
@Shyam-Chen may be you [mean `4.0.2`](https://www.npmjs.com/package/protractor)?

**Comment by Shyam-Chen** [comment]
Temporarily to close it.

default

**Pull request closed without merging**
