### PR TITLE
Performance improvements in the build

### PR DESCRIPTION
**Pull request by mgechev**
The current build in master is very slow because of:
- Introduced new set of tasks for the production build
- `ts-node` 5.4 seems a bit slower

Loading tasks on demand. Improve the initial build from 14 seconds to 8 seconds. Also provides better feedback to the user.

### CODE REVIEW

**Comment by tarlepp** [comment]
Nice speed improvement. Also I think that it would be very nice if actual watch task would only trigger necessary changes. Eg. if user modifies some .sass file there is no need to build whole project.

**Comment by ludohenin** [comment]
@tarlepp Incremental build will surely come soon :)

**Comment by ludohenin** [comment]
`npm start` starts the server but not the `watch` task

**Comment by mgechev** [comment]
Yep, thanks for the catch! The arrow function was creating troubles. It should be fine now (although one second slower :sob:)

**Comment by ludohenin** [comment]
Arrggfff ... there's an issue with `npm test` now. I can reproduce what travis' reporting.

**Comment by mgechev** [comment]
I'll fix that PR once I finish playing with the hot loader :-).

**Comment by mgechev** [comment]
@ludohenin are you still able to reproduce the `npm test` issue?

**Pull request merged**
