### PR TITLE
Fixing test failure due to angular2 dom location change

### PR DESCRIPTION
**Pull request by JakePartusch**
Fix for issue #78

### CODE REVIEW

**Comment by mgechev** [comment]
Are you using alpha37? I can't reproduce it.

**Comment by JakePartusch** [comment]
Yes, as you can see in the screenshot, `browser_adapter.js` and `dom_adapter.js` are in `src/core/dom`
 
screen shot 2015-09-16 at 7 43 46 am

**Comment by butterfieldcons** [comment]
yes, in alpha37 it moved as depicted above.

**Comment by ludohenin** [comment]
I also have the same issue.

**Pull request merged**
