### PR TITLE
Added check for required npm and node versions

### PR DESCRIPTION
**Pull request by tarlepp**
This solves #149

### CODE REVIEW

**Comment by tarlepp** [comment]
Hmm, seems like we need to install gulp before this, any ideas?

**Comment by tarlepp** [comment]
That was a bug from my side, let see if now all is okay.

**Comment by mgechev** [comment]
Looks good to me! How about making the check even before running `tsd --reinstall`?

If node/npm is not the version we need there's no point installing the ambient type definitions as well.

**Comment by tarlepp** [comment]
Actually if I move that ```gulp check``` to be first on that npm postinstall task. Version check will crash with following error (also note that this happen with _clean_ install, so there is no node_modules and those tsd files):

```
[12:45:17] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
----------------------------------

npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/home/wunder/.nvm/versions/node/v4.0.0/bin/node" "/home/wunder/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `gulp preinstall && tsd reinstall --clean && tsd link && tsd rebundle && gulp postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'gulp preinstall && tsd reinstall --clean && tsd link && tsd rebundle && gulp postinstall'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp preinstall && tsd reinstall --clean && tsd link && tsd rebundle && gulp postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wunder/projects/angular2-seed/npm-debug.log
```

**Comment by mgechev** [comment]
Oh, yeah sure...It makes sense it can't find the typing definitions for gulp. Merging.

**Pull request merged**
