### PR TITLE
WIP: Alpha 47 update

### PR DESCRIPTION
**Pull request by jesperronn**
Just want to share with you my progress so far for updating to angular2@alpha-47

Feel free to continue this work, as I have only limited capacity to work with it right now.

Here are the first notable changes.

* [ ] `browser_adapter` has been moved from core to platform in `test-main.js`
* [x] `dom_adapter` has been moved from core to platform
* [x] We no longer need typings shim for `dom_adapter`

NOTE still needs fix:
* [x] duplicate identifiers for node.d.ts in `node_modules/angular2/typings/node/node.d.ts` and `tools/typings/tsd/node/node.d.ts`
* [x] failing test with router (see error below)
* [x] failing test with `host_view` (see error below)

### failing test with `router`:

```
  App component
    ✖ should work
      PhantomJS 2.0.0 (Mac OS X 0.0.0)
      Chrome 48.0.2564 (Mac OS X 10.11.1)
    Failed: No provider for Token RouterPrimaryComponent! (RouterLink -> Router -> RouteRegistry -> Token RouterPrimaryComponent)
    Error: DI Exception
        at NoProviderError.BaseException [as constructor] (/Users/jesper/src/angular2-seed/node_modules/angular2/src/facade/exceptions.js:15:23)
        at NoProviderError.AbstractProviderError [as constructor] (/Users/jesper/src/angular2-seed/node_modules/angular2/src/core/di/exceptions.js:38:16)
        at new NoProviderError (/Users/jesper/src/angular2-seed/node_modules/angular2/src/core/di/exceptions.js:74:16)
```

### failing test with `host_view`:
```
 About component
    ✖ should work
      PhantomJS 2.0.0 (Mac OS X 0.0.0)
      Chrome 48.0.2564 (Mac OS X 10.11.1)
    Failed: Cannot read property 'hostView' of undefined
    TypeError: Cannot read property 'hostView' of undefined
        at new ComponentFixture_ (/Users/jesper/src/angular2-seed/node_modules/angular2/src/testing/test_component_builder.js:49:99)
        at /Users/jesper/src/angular2-seed/node_modules/angular2/src/testing/test_component_builder.js:215:52
        at Zone.run (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:120:17)
        at Zone.run (/Users/jesper/src/angular2-seed/node_modules/angular2/src/testing/testing.js:86:38)
        at zoneBoundFn (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:93:19)
        at lib$es6$promise$$internal$$tryCatch (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:1489:16)
        at lib$es6$promise$$internal$$invokeCallback (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:1501:17)
        at lib$es6$promise$$internal$$publish (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:1472:11)
        at /Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:201:5
        at microtask (/Users/jesper/src/angular2-seed/node_modules/angular2/src/testing/testing.js:100:25)
        at Zone.run (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:120:17)
        at Zone.run (/Users/jesper/src/angular2-seed/node_modules/angular2/src/testing/testing.js:86:38)
        at zoneBoundFn (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:93:19)
        at MutationObserver.lib$es6$promise$asap$$flush (/Users/jesper/src/angular2-seed/node_modules/zone.js/dist/zone-microtask.js:1283:9)
    Failed: Cannot read property 'detectChanges' of undefined
    TypeError: Cannot read property 'detectChanges' of undefined
        at /Users/jesper/src/angular2-seed/test/components/app/app_spec.js:34:23
```

### CODE REVIEW

**Comment by mgechev** [comment]
Looks great! Looking forward for merging it!

**Comment by sclausen** [comment]
@mgechev: I cloned the angular2 fork from @jesperronn and fixed the router-issue in the alpha_47_update branch, but how do I contribute now?

**Comment by mgechev** [comment]
@sclausen I did the same but there are plenty of typing errors yet.

**Comment by jesperronn** [comment]
Thanks a lot for the improvements. I really appreciate it! Did any of you try alpha-50 yet?

**Comment by sclausen** [comment]
@jesperronn I tried alpha.50 and beside changing some test configuration and the thing in the application test everything seems to work fine.

**Comment by sclausen** [comment]
@mgechev I don't think getting rid of the duplicate identifiers error would require a nasty hack.
per default gulp-typescript tries to resolve required files and I think this is a nasty hack. We should add the option `noExternalResolve` to createProject in utils and add the definition folders to the source files.

**Comment by mgechev** [comment]
@sclausen you're right, nasty hacks weren't required. `noExternalResolve` will prevent developers from using `<reference src="..."/>` in their `.ts` files.

@jesperronn thanks for the PR! We struggled with the typing errors and it seems we made it work here https://github.com/mgechev/angular2-seed/pull/286.

**Comment by jesperronn** [comment]
Awesome work guys!

**Pull request closed without merging**
