### PR TITLE
added Virtual Component Proxy example

### PR DESCRIPTION
**Pull request by sclausen**
I added the slightly cleaned Virtual Proxy Example from [mgechevs blog](http://blog.mgechev.com/2015/09/30/lazy-loading-components-routes-services-router-angular-2/). 
Unfortunately I have absolutely no clue how one could write a test for this scenario.

### CODE REVIEW

**Comment by mgechev** [comment]
Thank you for the PR! Some of the API that you are using is currently deprecated (`bindigs` -> `providers`, `bind` -> `provide`).

Your implementation is good, however, I'm wondering if we have to add multiple examples to the seed or keep them in another repository instead. This is the topic of the discussion here https://github.com/mgechev/angular2-seed/issues/308

**Comment by Bigous** [comment]
Nice, @sclausen !
I couldn't figure out how to reflect this to gulp in build.prod ... any hint?

**Comment by sclausen** [comment]
@Bigous its a bit difficult, since the current build process bundles everything and the lazy loading approach would be a bit more like the current dev process with optimization for the libs.

@ludohenin @NathanWalker : I'm stuck with satisfying the typescript linter regarding systemjs.
How do I use this typing?

``` typescript
// Type definitions for System.js 0.18.4
// Project: https://github.com/systemjs/systemjs
// Definitions by: Ludovic HENIN <https://github.com/ludohenin/>, Nathan Walker <https://github.com/NathanWalker/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

interface System {
  import(name: string): any;
  defined: any;
  amdDefine: () => void;
  amdRequire: () => void;
  baseURL: string;
  paths: { [key: string]: string };
  meta: { [key: string]: Object };
  config: any;
}

declare var System: System;

declare module "systemjs" {
  export = System;
}
```

``` typescript
  class VirtualComponent {
    constructor(
      el: ElementRef,
      loader: DynamicComponentLoader,
      inj: Injector,
      provider: ComponentProvider
    ) {
        System.import(provider.path)
        .then(m => {
          loader.loadIntoLocation(provider.provide(m), el, 'content');
        });
      }
  }
```

**Comment by mgechev** [comment]
Closing it, I saw you already added example in the AngularShowcase sample app repo.

**Comment by Bigous** [comment]
Just for documentation, [here is the repository](https://github.com/AngularShowcase/angular2-sample-app)

**Pull request closed without merging**
