### PR TITLE
add logs for server startup

### PR DESCRIPTION
**Pull request by dwido**
It would be very helpful to know which port is running from the startup task

### CODE REVIEW

**Comment by mgechev** [comment]
Would you use the log function from gulp utils and capitalize server?

**Comment by dwido** [comment]
Good point!

**Comment by dwido** [comment]
@mgechev I have committed a change, not sure why checks are failing

**Comment by alalek** [comment]
@dwido There is a merge conflict, please update your changes.
You may use `git pull --rebase` (or `git pull --rebase upstream master`) command to do this.
During conflict resolving you need to remove this line from `tools/utils/server.ts`:
```
import * as connectLivereload from 'connect-livereload';
```

**Comment by mgechev** [comment]
@dwido thanks for the PR!

**Pull request merged**
