### PR TITLE
Update code documentation and manual typings

### PR DESCRIPTION
**Pull request by TheDonDope**
Hey guys, 
this commit fixes some minor formatting issues with the jsdoc notation. Furthermore it corrects some linting errors in the manual typings.

Details on the fixes:

**JSDoc:**
- Use full 120 character line length (in accordance with tslint configuration)
- Use `@param {type} paramName - The description.` Syntax 
- Move class documentation above Annotations (like `@Component` or `@Injectable`) for better readability

**Manual Typings:**
- Fixes linting error `no new endline at the end of a file`
- Fixes error in `express-history-api-fallback.d.ts` (replacing `,` with `;`)

Greetings

Dope

### CODE REVIEW

**Comment by ludohenin** [comment]
Awesome!

**Comment by TheDonDope** [comment]
@ludohenin Thanks :) Unfortunately the AppVeyor build failed (quite often lately), again with the typical timing problem leading to the failed comparison of the name-list contents. Is there some way to retrigger a build?

**Comment by ludohenin** [comment]
Don't know how to restart the build.

**Comment by ludohenin** [comment]
It's failling with Chrome only and the assertion looks OK, don't know why it complains.
I'll merge.

**Pull request merged**
