### PR TITLE
Fix running PhantomJS in Ubuntu 15.10

### LINKED ISSUE #314: npm test fails on Ubuntu 15.10
Running test on my Ubuntu 15.10 fails with the error:
```
START:
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
INFO [launcher]: Starting browser Chrome
ERROR [launcher]: Cannot start PhantomJS2
	
INFO [launcher]: Trying to start PhantomJS2 again (1/2).
ERROR [launcher]: Cannot start PhantomJS2
	
INFO [launcher]: Trying to start PhantomJS2 again (2/2).
ERROR [launcher]: Cannot start PhantomJS2
	
ERROR [launcher]: PhantomJS2 failed 2 times (cannot start). Giving up.
```
Unfortunately, no additional info why PhantomJS2 can't be started was given :disappointed:
If you encounter this problem, you should execute `node_modules/phantomjs2-ext/bin/phantomjs` directly and see which lib is still missing.
With Ubuntu 15.10, my system missed `libicu52`. Older Ubuntu versions do have this lib in their repositories, but as of 15.10 one has to load it e.g. from here http://packages.ubuntu.com/trusty/amd64/libicu52/download
A friend of mine with arch-linux also missed `libpng12`, so, if you encounter this problem, run phantomjs directly and see whats missing.

### PR DESCRIPTION
**Pull request by pgrzeszczak**
This fixes #314. Newer version of karma-phantomjs2-launcher can run tests in Ubuntu 15.10

### CODE REVIEW

**Comment by antonybudianto** [comment]
it's now deprecated, you should upgrade to official [karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/CHANGELOG.md)

**Comment by d3viant0ne** [comment]
Agreed

**Comment by mgechev** [comment]
@pgrzeszczak would you fix the merge conflict and the failing build?

**Comment by pgrzeszczak** [comment]
Fixed, now it looks ok.

**Comment by d3viant0ne** [comment]
@pgrzeszczak - Thanks :)

**Pull request merged**
