### PR TITLE
Update to beta.2

### PR DESCRIPTION
**Pull request by mgechev**
Changes:
- Update the angular2 and angular2-hot-loader packages versions.
- Update the tests according to the latest [breaking changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes).
- Update the SystemJS config in order to speedup the dev build page load time.
- Merged with https://github.com/mgechev/angular2-seed/pull/411.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Excellent. lgtm.

**Comment by ludohenin** [comment]
Will check that tonight and merge.

**Comment by ludohenin** [comment]
@mgechev I'm getting this error when runing `npm test`
```bash
ERROR: 'Cannot set base providers because it has already been called
	Evaluating http://localhost:9876/base/test/about/components/about_spec.js
	Error loading http://localhost:9876/base/test/about/components/about_spec.js'
```

**Comment by mgechev** [comment]
@ludohenin thanks! I'll take a look tonight and fix the problems.

**Comment by NathanWalker** [comment]
Just pushed up the fix for the tests. @ludohenin thx for the catch.

**Comment by mgechev** [comment]
@NathanWalker haha, didn't see your change. Let me revert back.

**Comment by NathanWalker** [comment]
@mgechev lol nice! ... I think using the Promise.all is a little more scalable and easier to maintain if we end up needing to setup more things globally for tests :)

Also, the IE errors are still not fixed in `beta.2` unfortunately:
https://github.com/angular/angular/issues/6501

However, a workaround posted there suggests this:
> As @sanbornc commented, adding the following lines in a script tag or JS file before the loading of any other libraries will fix the problem for IE. (as a temporary fix for beta.1)
**and beta.2**
```
if (!Object.hasOwnProperty('name')) {
  Object.defineProperty(Function.prototype, 'name', {
    get: function() {
      var matches = this.toString().match(/^\s*function\s*(\S*)\s*\(/);
      var name = matches && matches.length > 1 ? matches[1] : "";
      Object.defineProperty(this, 'name', {value: name});
      return name;
    }
  });
}
```
We may consider using the workaround so we can have the fast load times on dev until fixed by subsequent beta release?

**Comment by NathanWalker** [comment]
Speaking of tests, I would greatly appreciate your insight here:
https://github.com/mgechev/angular2-seed/issues/422  ;)

**Comment by NathanWalker** [comment]
This squashed commit looks like it went back to the callback ladder of demise :/
https://github.com/mgechev/angular2-seed/commit/71cac79576b2da94f89d54adffd29802078a8025

**Comment by NathanWalker** [comment]
for ref:
```
Promise.all([
  System.import('angular2/src/platform/browser/browser_adapter'),
  System.import('angular2/testing'),
  System.import('angular2/platform/testing/browser')
])
  .then(function (modules) {
    var browser_adapter = modules[0];
    browser_adapter.BrowserDomAdapter.makeCurrent();
    var testing = modules[1];
    var browser = modules[2];
    testing.setBaseTestProviders(
      browser.TEST_BROWSER_PLATFORM_PROVIDERS,
      browser.TEST_BROWSER_APPLICATION_PROVIDERS);
    return Promise.all(
      Object.keys(window.__karma__.files) // All files served by Karma.
```

**Comment by jesperronn** [comment]
df2ce0cf2c946ff83f398d1b315ecab3814c6843 works for me. LGTM. @mgechev, @NathanWalker I really like the cleanup in all the test files. Awesome idea to move the initialization to test-main.js :+1:

**Comment by NathanWalker** [comment]
wow, that patch worked for IE. excellent :100: 
lgtm!

**Comment by mgechev** [comment]
@NathanWalker would you also update the [wiki](https://github.com/mgechev/angular2-seed/wiki) to use typings instead of tsd?

**Comment by NathanWalker** [comment]
@mgechev I had changed it yesterday pre-merge; just modified it again though to ensure `typings` was linked in the wiki like it is in the readme though :+1:

**Comment by mgechev** [comment]
@NathanWalker awesome!

**Pull request merged**
