### PR TITLE
Revert "Lazy load gulp tasks"

### PR DESCRIPTION
**Pull request by mgechev**
Reverts mgechev/angular2-seed#313

### CODE REVIEW

**Comment by ludohenin** [comment]
:)

**Comment by lihaibh** [comment]
?

**Comment by mgechev** [comment]
@lihaibh https://github.com/mgechev/angular2-seed/issues/318

**Comment by stefanocke** [comment]
@lihaibh , @mgechev  I think the reason for #318 is that the build tasks were made asynchronous "twice" by the PR: They already returned pipes before and you added the "done" parameter, but you never called done(). I am by far not a gulp expert, but I tried the following and it seems to work so far:

```
export function task(taskname: string, option?: string) {
  return () => {
    util.log('Loading task', chalk.yellow(taskname, option));
    return require(join('..', 'tasks', taskname))(gulp, gulpLoadPlugins(), option)();
  };
}
```
So, compared to the PR, I just removed the "done" parameter.

**Comment by stefanocke** [comment]
P.S.: Sorry, spoken a bit to early: My approach does not work for the tasks, that don not return pipes and expect the done parameter, for example build.bundles. Nevertheless: Passing the "done" parameter into tasks, that do not expect it, is the reason for #318.

**Comment by lihaibh** [comment]
Ye... ive added the 'done' handler in favor of tasks like 'clean' that use it, i assumed it will work because gulp passing this callback by default so at the time when i squashed my commits i added this change.
I forgot to run 'sanity checks' after this change and thats why it happened, thanks for the report.

**Pull request merged**
