### PR TITLE
TypeDoc -  Generate the api documentation for the application.

### PR DESCRIPTION
**Pull request by natarajanmca11**
It generates the simple Api documents to the application.

### CODE REVIEW

**Comment by mgechev** [comment]
Looks cool! Would you rebase and make the build pass?

**Comment by natarajanmca11** [comment]
Today will do it

**Comment by ludohenin** [comment]
@natarajanmca11 Would you clean up commit history (it's a bit too messy ;)

**Comment by NathanWalker** [comment]
Closing this since https://github.com/mgechev/angular2-seed/pull/180 is the same thing with cleaned up git history.

**Pull request closed without merging**
