### PR TITLE
Small fixes.

### PR DESCRIPTION
**Pull request by tarlepp**
1) Removed some not needed ;
2) Some code syntax changes

### CODE REVIEW

**Comment by mgechev** [comment]
Are these changes according to the coding style or just your personal preferences/

**Comment by tarlepp** [comment]
Removing not needed ```;``` is just something that IDE's will complain (if those exists), other things are done according to https://github.com/airbnb/javascript, which is basically standard.

**Comment by ludohenin** [comment]
I find original indentation a lot easier to read. Guidelines are good but redability first imo.

**Comment by tarlepp** [comment]
ok, will revert those identations changes.

**Comment by mgechev** [comment]
Lets close this PR for now.

PS: I just want to mention that redundant use of semicolons is not always a drawback https://github.com/twbs/bootstrap/issues/3057

**Comment by tarlepp** [comment]
ok, imho those should follow same syntax in all files, eg. now there is tasks files with and without these not needed semicolons. Just trying to harmonize those. eg.

https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.csslib.dev.ts#L9
https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.index.dev.ts#L21

**Comment by mgechev** [comment]
Yes, I agree with you for following a consistent coding style. Semicolons are common for function expressions so this seems like more proper way to proceed https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.index.dev.ts#L21.

I can reopen this PR, you can fix all the inconsistencies you find and squash. Does this sounds alright to you?

**Comment by tarlepp** [comment]
ok, will check all those. Also I need to make some default config changes to my IDE (IntelliJ IDEA) for not to complain these "errors", basically IDE is saying:

```
Unnecessary semicolon less... (Ctrl+F1) 
Checks JavaScript source code for unneeded semicolons . The validation works in JavaScript, html 
or jsp files.
```
And that was the reason why I removed those. Semicolons are ok, if you're making eg. ```let somefunction = function () { .... }; but if it's export those are not needed.

**Comment by tarlepp** [comment]
Changes made to that branch. https://github.com/tarlepp/angular2-seed/commit/1ce1dc2e3773abedeb6335dd34df7a3b647f181f

**Comment by mgechev** [comment]
LGTM, would you create a pull request with that branch?

**Pull request closed without merging**
