### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ludohenin**
* typings
  * No need to install typings
  * Move `app/typings` to `tools`
  * Move `tsd_typings` to `tools`
  * TODO: Open issue #xxx about `app/typings.d.ts`

* app
  * Move `AppCmp` to `app/components/app`
  * Add `bootstrap.ts`
  * Move `init.ts` to `index.html`
  * Rename all components class name by `{cmpname}Cmp`

* package.json
  * Add scripts:
    * "build.dev": "gulp build.dev",
    * "build.dev.watch": "gulp build.dev.watch",
    * "build.test": "gulp build.test",
    * "build.test.watch": "gulp build.test.watch",
    * "gulp": "gulp",
    * "karma": "karma",
    * "karma.start": "karma start",
    * "lint": "gulp tslint",
    * "postinstall": "gulp postinstall",
    * "start": "npm run serve.dev",
    * "serve.dev": "gulp serve --env dev",
    * "tasks.list": "gulp --tasks-simple",
    * "test": "gulp test",
    * "tsd": "tsd"

* utils
  * Modularize
  * Add asset injection method `registerInjectableAssetsRef`
  * Add task tools - exports `autoRegisterTasks` & `task`

* tasks
  * Modularize
  * tasks available by default:
    * build.css.dev
    * build.dev
    * build.dev.watch
    * build.fonts
    * build.index.dev
    * build.js.dev
    * build.lib.dev
    * build.sass.dev
    * build.test
    * build.test.watch
    * clean
    * clean.dist
    * clean.test
    * karma.start
    * npm
    * postinstall
    * serve
    * server.start
    * test
    * tsd
    * tslint
    * watch.dev
    * watch.serve
    * watch.test

### CODE REVIEW

**Comment by ludohenin** [comment]
oops ... Maybe I have to remove bootstrap ?

**Comment by ludohenin** [comment]
It's also maybe a good time to add a quick CHANGELOG.md

**Comment by mgechev** [comment]
I'll review it today

**Comment by mgechev** [comment]
It might be a good idea to remove bootstrap. I guess most people would use Angular 2 with Material.

But lets keep it for now.

**Comment by mgechev** [comment]
Can't we use tsd for fetching the type definitions? Do we need to push them to the repository?

**Comment by ludohenin** [comment]
I found it easier to keep it as it is. no preinstall script required and faster install (though subjective and maybe not that significant). it is running `tsd reinstall --clean` to make sure it is clean after a local update.

**Comment by ludohenin** [comment]
we can re-introduce preinstall, I don't mind.

**Comment by jgodi** [comment]
Doesn't that go away with the latest alpha version? 

`TypeScript typings are now included in the distribution. If you have installed external typings (eg. using tsd to fetch files from DefinitelyTyped), you need to remove them. TypeScript will give a Duplicate identifier error if the same type definition appears twice.`

**Comment by mgechev** [comment]
Lets keep preinstall, keeping the type definitions of external libraries seems too redundant to me.

**Comment by ludohenin** [comment]
ok

**Comment by tarlepp** [comment]
Hmm if you're interested to make CHANGELOG.MD for this repo, I recommend that you start to use eg. https://github.com/skywinder/github-changelog-generator to make things easier.

**Comment by ludohenin** [comment]
@mgechev [preinstall typings](https://github.com/mgechev/angular2-seed/commit/0f6adc25eb21ed4190ac7c9def222931d7afc9f9). Is that ok ?

**Comment by mgechev** [comment]
Ups, I think after the merge I broke the build https://travis-ci.org/mgechev/angular2-seed/jobs/85574996

**Comment by tarlepp** [comment]
Hmm, I'll try to add tsd install to travis config, that should solve this.

**Comment by tarlepp** [comment]
was wrong with that tsd installation, fix was to use local path for tsd PR #161

**Pull request merged**
