### PR TITLE
(fix): Uses es6-shim to fix 'undefined' errors in Safari

### PR DESCRIPTION
**Pull request by markharding**
Safari throws the following error because angular2 references `startsWith` which doesn't exist. 

I've replaces es6-module-loader with es6-shim(https://github.com/paulmillr/es6-shim).

Question:

- [ ] Do we still rely on `system-polyfills.js`?
- [ ] Do we still rely on `Reflect.js`?

```
[Error] EXCEPTION: TypeError: undefined is not an object (evaluating 'styles.forEach')
    logError (angular2.dev.js, line 19115)
    logGroup (angular2.dev.js, line 19126)
    call (angular2.dev.js, line 4440)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] STACKTRACE:
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4442)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] addStyles@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:17408:13
registerComponentTemplate@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:25506:44
_createComponent@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26637:49
createComponent@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26682:45
visitBeginComponent@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26724:44
visit@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10268:41
visitAllCommands@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10317:20
_initializeProtoView@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26662:43
initializeProtoViewIfNeeded@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:26657:34
createRootHostView@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:21008:57
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:13176:64
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$$internal$$tryCatch@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1507:24
lib$es6$promise$$internal$$invokeCallback@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1519:52
lib$es6$promise$$internal$$publish@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1490:52
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:219:7
microtask@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10598:19
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$asap$$flush@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1301:17
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4443)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] EXCEPTION: TypeError: undefined is not an object (evaluating 'componentRef.location')
    logError (angular2.dev.js, line 19115)
    logGroup (angular2.dev.js, line 19126)
    call (angular2.dev.js, line 4440)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] STACKTRACE:
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4442)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] http://localhost:5555/lib/angular2.dev.js?v=0.0.0:19728:42
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$$internal$$tryCatch@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1507:24
lib$es6$promise$$internal$$invokeCallback@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1519:52
lib$es6$promise$$internal$$publish@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1490:52
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:219:7
microtask@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10598:19
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$asap$$flush@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1301:17
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4443)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] EXCEPTION: TypeError: undefined is not an object (evaluating 'componentRef.hostView')
    logError (angular2.dev.js, line 19115)
    logGroup (angular2.dev.js, line 19126)
    call (angular2.dev.js, line 4440)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] STACKTRACE:
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4442)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
[Error] tick@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:19896:73
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$$internal$$tryCatch@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1507:24
lib$es6$promise$$internal$$invokeCallback@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1519:52
lib$es6$promise$$internal$$publish@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1490:52
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:219:7
microtask@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10598:19
run@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:138:22
http://localhost:5555/lib/angular2.dev.js?v=0.0.0:10572:37
zoneBoundFn@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:111:22
lib$es6$promise$asap$$flush@http://localhost:5555/lib/angular2.dev.js?v=0.0.0:1301:17
    logError (angular2.dev.js, line 19115)
    call (angular2.dev.js, line 4443)
    (anonymous function) (angular2.dev.js, line 19823)
    _onError (angular2.dev.js, line 10639)
    onError (angular2.dev.js, line 10558)
    run (angular2.dev.js, line 141)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
    lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519)
    lib$es6$promise$$internal$$publish (angular2.dev.js, line 1490)
    (anonymous function) (angular2.dev.js, line 219)
    microtask (angular2.dev.js, line 10598)
    run (angular2.dev.js, line 138)
    (anonymous function) (angular2.dev.js, line 10572)
    zoneBoundFn (angular2.dev.js, line 111)
    lib$es6$promise$asap$$flush (angular2.dev.js, line 1301)
```

### CODE REVIEW

**Comment by mgechev** [comment]
`Reflect` is required because of the decorators support.

`system-polyfills` contain `URLPolyfill`, which is required for System.js

**Comment by markharding** [comment]
It looks like Reflect is included in es6-shim - https://github.com/paulmillr/es6-shim

**Comment by ryzy** [comment]
BTW I noticed we add all `.map` files in `lib_inject` section. Does it really make sense? They are not injected anyway into HTML file...

They should be moved to `lib_copy_only`, don't you think?

**Comment by ludohenin** [comment]
@ryzy right. Good catch.
In the refactored build I'm working on, I've added a filter to skip .map (that's another way/control)

**Pull request merged**
