### PR TITLE
Circleci test setup

### PR DESCRIPTION
**Pull request by jesperronn**
It could add value to users of the seed project, that they can easily setup build on CircleCI

* [x] added circle.yml configuration
* [x] modified karma.config so that it runs Chrome (same as Travis)

**A note on Headless PhantomJS**: Making the build to run headless PhantomJS2 is not working for me (but is also a topic for a separate issue/PR)

In case you are interested, here is the passing CircleCI build for the fix 
https://circleci.com/gh/jesperronn/angular2-seed/9

### CODE REVIEW

**Comment by jesperronn** [comment]
Note that the **failing test is due to #176 and seems unrelated** to this particular pull-request.

**Comment by jesperronn** [comment]
@mgechev let me know if you want to merge this? If not It's just to close this PR. It can then serve as an example for people who want to use CircleCI

**Comment by mgechev** [comment]
LGTM. Would you squash to a single commit?

**Comment by jesperronn** [comment]
Failing with 'Github rate exceeded'

See #176 `tsd reinstall` fails with 'Github rate exceeded' and #200

**Pull request merged**
