### PR TITLE
[WIP] chore(devDeps): Update dev dependencies

### PR DESCRIPTION
**Pull request by Shyam-Chen**
#985

### CODE REVIEW

**Comment by TheDonDope** [comment]
We better should not update dev dependencies until #959 is resolved. Updating the deps could possibly break something.

**Comment by mgechev** [comment]
SystemJS builder newer than the current version introduces issue on windows https://github.com/mgechev/angular2-seed/issues/975.

**Comment by Shyam-Chen** [comment]
@mgechev  remove `check.versions` task?

**Comment by TheDonDope** [comment]
@Shyam-Chen why would we want to remove the `check.version` task?

**Comment by TheDonDope** [comment]
Also again: We should **not** introduce yet another refactor / dependency update until #959 is resolved.. That already is a huge refactor and merging it back to `master` should not introduce more / new merge conflicts.

**Comment by Shyam-Chen** [comment]
@TheDonDope can be recorded

**Pull request closed without merging**
