### PR TITLE
[WIP] Offline compilation

### PR DESCRIPTION
**Pull request by ludohenin**
In connection with @mgechev proposal for an Advanced production build #864. 
This PR is basically here just to share what's I've found about the newly released offline compilation feature.

What I've done:
* Added a task `offline.compilation`
* Changed component template/styles to relative urls (only supported so far) (see [angular/angular#8624](https://github.com/angular/angular/issues/8624))
* Updated `main.ts` and a bunch of other thinks to make it not crash (see [angular/angular#8625](https://github.com/angular/angular/issues/8625))

If you want to try it, you'll have to manually update `node_modules/@angular/router/index.d.ts` (fixed in the angular repo but not yet published).
```ts
// Change in L35
export declare const ROUTER_DIRECTIVES: any[];
// to
export declare const ROUTER_DIRECTIVES: [RouterOutlet, RouterOutlet];
```

One thing I really don't understand is why the generated `*.ngfactory.ts` files try to import their original component.

//cc @mgechev @d3viant0ne @NathanWalker

### CODE REVIEW

**Comment by NathanWalker** [comment]
@ludohenin bravo for trying to tackle at this stage. Excited to see this working! If there are known issues or a to-do list that could be broken amongst to help reach this end goal, please let us know.

**Comment by ludohenin** [comment]
@NathanWalker It's simply broken for now. I don't think we can make it work, though not sure. What I'd like to have clarification on is it's normal that the generated file wants to import it's source file (looking at the codegen doesn't help much).

**Comment by ludohenin** [comment]
I think I need help here. Do not hesitate to push commit in that branch.

**Comment by taguan** [comment]
Hello, I would like to help you for this.
Could you explain what is the status of your branch and where I can find any form of documentation about that angular offline compilation feature ?

**Comment by mgechev** [comment]
@taguan you can take a look here https://github.com/angular/angular/tree/master/modules/%40angular/compiler_cli

**Comment by taguan** [comment]
I am running on endless issues just trying to run ngc on the seed project (I guess you experimented the same kind of issues as I see you commented the name-list service in the home component). I have the feeling that the offline compilation feature is not ready yet, but maybe I am doing things wrong...

**Comment by ludohenin** [comment]
@taguan Yes that's also my feeling, good that you crossed checked it.

**Comment by sfabriece** [comment]
What's the difference between angular universal and offline compilation?

**Comment by mgechev** [comment]
@ludohenin lets close this PR because it already has a lot of merge conflicts already. I agree with you that we might want to add the integration on later stage.

**Comment by Luchillo** [comment]
Hi, how's this going, since RC3 the `@angular/compiler-cli` is included in the package so maybe now would be less problematic to make this work, are you going to try soon? i did but since i'm using webpack, the need for the app component to be precompiled as a factory makes it hard for me to try this, and trying to call the compiler on that file before the compilation gives me this kind of error:

```sh
TypeError: Cannot read property 'getSymbolsInScope' of undefined
    at MetadataCollector.getMetadata (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/tsc-wrapped/src/collector.js:149:34)
    at ReflectorHost.getMetadataFor (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/compiler-cli/src/reflector_host.js:156:47)
    at StaticReflector.getModuleMetadata (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/compiler-cli/src/static_reflector.js:424:40)
    at CodeGenerator.readComponents (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/compiler-cli/src/codegen.js:44:51)
    at generateOneFile (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/compiler-cli/src/codegen.js:100:38)
    at Array.map (native)
    at CodeGenerator.codegen (/Users/aplicaciones2/Documents/Ng2WebpackProStarter/node_modules/@angular/compiler-cli/src/codegen.js:127:14)
```

**Comment by mgechev** [comment]
This is [an issue](https://github.com/angular/angular/issues/9540) in ngc.

**Comment by Luchillo** [comment]
I see, is the planned process still the same? run ngc on app component first to get it's factory then run tsc in whole component as explained here?: [offline-compilation-in-angular-2.0](http://www.syntaxsuccess.com/viewarticle/offline-compilation-in-angular-2.0)

**Pull request closed without merging**
