### PR TITLE
Updated dev dependencies.

### PR DESCRIPTION
**Pull request by tarlepp**
Updated clean task to use promises.
Karma isn't updated, because newer version TSD typings contains some errors.

### CODE REVIEW

**Comment by tarlepp** [comment]
Tests are failing because of GitHub rate limit, solution for this in #176 Screenshot from my vm running those tests.

image

**Comment by jesperronn** [comment]
I also see that ts-node has a new update:
```
ts-node               😎  NEW VER!  NonSemver update available: https://github.com/TypeStrong/ts-node
                                   npm install --save-dev ts-node@0.4.0 to go from 0.2.5 to 0.4.0
```

**Comment by tarlepp** [comment]
Not yet merged?

**Comment by mgechev** [comment]
@tarlepp there's a merge conflict. Would you resolve it in order to merge?

**Pull request closed without merging**
