### PR TITLE
Alpha44

### PR DESCRIPTION
**Pull request by ludohenin**
Tests are still broken due to Angular 2 `AsyncTestCompleter`

### CODE REVIEW

**Comment by ludohenin** [comment]
// cc @NathanWalker @tarlepp

**Comment by ludohenin** [comment]
rebased & squashed

// cc @mgechev

**Comment by mgechev** [comment]
Needs to be rebased again. Lets merge & tag alpha42 first.

**Comment by ludohenin** [comment]
Will update 42 this afternoon.

**Comment by mgechev** [comment]
The build is failing, would you fix it to merge and tag?

**Comment by ludohenin** [comment]
yep, will do that this evening.
Build fails due to github api limit rate, but there is also an issue with path to reactivex dep.

**Comment by mgechev** [comment]
Okay, I'll merge it tomorrow :-)

**Comment by ludohenin** [comment]
oops I did something wrong.

**Comment by ludohenin** [comment]
I merged accidentally but I think it's fine. There is still an issue with travis (non blocking) as the tests are passing but only one is executed (NameList_spec but none of the Cmp_spec). Path to reactivex seems different to what I have on my machine.
What do you guys' have `node_modules/angular2/node_modules/@reactivex` or `node_modules/@reactivex` ?

**Pull request closed without merging**
