### PR TITLE
chore(devDeps): Update dev dependencies

### LINKED ISSUE #741: chore(devDeps): Update dev dependencies
**Major**
- stylelint-config-standard to 5.0.0
  - Removed: font-family-name-quotes, function-url-quotes and string-quotes rules

**Minor**
- tslint to 3.7.1
  - Enhancements & new rules / rule options
- stylelint to 5.3.0
  - Various rule fixes
  - SugarSS & Less syntax support
- colorguard to 1.1.1
  - Upstream dependency updates

**Patch**
- ts-node to 0.7.1
  - Fix for absolute paths
- typings to 0.7.12
  - Improve deprecation and open messages
- chalk to 1.1.3
  - Improve deprecation and open messages

**Associated Fixes**
- Fixed style error in toolbar.component.css ( stylelint update )

### PR DESCRIPTION
**Pull request by d3viant0ne**
List of updates & reasons in #741 or the commit messages

Includes one style fix post stylelint update

Resolves #741

### CODE REVIEW

**Comment by mgechev** [comment]
@d3viant0ne would you squash to a single commit?

**Comment by d3viant0ne** [comment]
:)

**Comment by mgechev** [comment]
I forgot about the squash button.. :-)

**Comment by d3viant0ne** [comment]
lol...So did i

**Pull request merged**
