### PR TITLE
Protractor CI

### PR DESCRIPTION
**Pull request by Shyam-Chen**
#732

### CODE REVIEW

**Comment by mgechev** [comment]
Yes, no worries. You can experiment here and once you have success you can squash and I'll merge.

Thanks for the effort!

**Comment by Shyam-Chen** [comment]
##### Known Issues
* sauce not connect

I guess this not my project (cause)

**Comment by Shyam-Chen** [comment]
default

**Comment by mgechev** [comment]
Do you need `SAUCE`? You should be able to run e2e tests in CI only with travis config change https://coderwall.com/p/1ny7nq/running-protractor-tests-with-a-headless-browser-on-travis-ci.

**Comment by mgechev** [comment]
@Shyam-Chen I see that the test is now executed in travis! Congratz! Looking forward for further progress! :-)

**Comment by Shyam-Chen** [comment]
@mgechev karma.start can't find  `Finished` log

https://travis-ci.org/mgechev/angular2-seed/builds/121899189#L344

**Comment by Shyam-Chen** [comment]
I do not know why this is so
default

I think after reprocessing

**Pull request closed without merging**
