### PR TITLE
Updated to Alpha 42

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by mgechev** [comment]
Travis complains about something. Would you fix the build and push your changes?

**Comment by NathanWalker** [comment]
Hmm, I'm not sure why Travis fails at installing npm modules. @tarlepp do you know why my PR is failing with Travis?

This is the error:
```
> angular2-seed@0.0.0 test /home/travis/build/mgechev/angular2-seed
> gulp test
[16:36:11] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript
gulpfile.ts (2,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (15,10): Cannot find name 'require'. (2304)
----------------------------------
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

It appears it did not properly install `gulp` and other node_modules?

**Comment by tarlepp** [comment]
Hmm, sounds weird because other travis builds are passing.

**Comment by tarlepp** [comment]
Actually if you compare https://travis-ci.org/mgechev/angular2-seed/jobs/85365711#L106 and https://travis-ci.org/mgechev/mgechev/angular2-seed/jobs/85079139#L99 it seems like ```node ./tools/postinstall``` is failing. If I remember correct someone else did have this same issue.

You can run tests on your own environment? Could you check that with clean install too?

**Comment by NathanWalker** [comment]
Hmm it may be related to the typings change in alpha 42, not sure:
https://docs.google.com/document/d/1LvPBh7yxmjr7N1vCQ-kBj4guZGfGLBiz44CfenOX6o0/preview

I won't have time to try anything else tonight but can look again tomorrow. If anybody else gets into this tonight, feel free to pull the PR and fix it up :+1:

**Comment by NathanWalker** [comment]
No need for this anymore. I'll look at some of the latest alpha releases and may wait to PR any more updates to this repo until last update is released before AngularConnect. :+1:

**Pull request closed without merging**
