### PR TITLE
Update to RC2

### PR DESCRIPTION
**Pull request by kiuka**
Update deprecated router to 3.0.0-alpha.6

### CODE REVIEW

**Comment by mgechev** [comment]
@kiuka would you fix the failing build? It seems like a minor linting error.

**Comment by Shyam-Chen** [comment]
`src/client/app/app.component.spec.ts(11,39): error TS2307: Cannot find module '@angular/router/testing'.`

**Comment by kiuka** [comment]
hmm, it seems there is no testing directives for the new router yet. what should we do?

**Comment by kiuka** [comment]
I have no idea how to pass the tests. It needs the fake router providers of the new router, and disable the old forms.

**Comment by mgechev** [comment]
You can take a look at the following set of [fake providers](https://github.com/angular/angular/blob/master/modules/%40angular/router/testing/router_testing_providers.ts).

**Comment by kiuka** [comment]
@mgechev yes, but it is not provided by the new router:(

**Comment by kiuka** [comment]
I fixed the issue with the router, but I still can't get rid of the Warnings about depracated forms. I have found examples (https://github.com/angular/angular/tree/master/modules/%40angular/forms/test), how to test forms, but it doesn't work that I tried:(

If anyone have any idea how to handle the warning, please share with me:)

**Comment by mgechev** [comment]
LGTM

**Comment by vip32** [comment]
and now [RC3](http://angularjs.blogspot.de/2016/06/rc3-now-available.html) just got released

**Comment by mgechev** [comment]
Yes, the seed is already using it.

**Comment by vip32** [comment]
you are great :)

**Pull request merged**
