### PR TITLE
feat(build): add ahead-of-time compilation

### PR DESCRIPTION
**Pull request by mgechev**
I think the AoT in RC.6 is stable enough to merge to master. In case we experience any issues we can anytime revert back to https://github.com/mgechev/angular2-seed/commit/de5cbaf32a7291980975e2241b2c880b800e7a32.

// cc @ludohenin @TheDonDope @NathanWalker @Bigous @d3viant0ne

### CODE REVIEW

**Comment by mgechev** [comment]
FYI, I considered the JavaScript version of the Google Closure Compiler but unfortunately it's not able to process the generated from `ngc` output (get "Unexpected token =").

**Comment by TheDonDope** [comment]
Hey Minko! Thank you so much for your work on this topic! I will give it a drive. I think it would be nice to have a short section in the README on how to use the AoT? 

Greetings

Dope

**Comment by ludohenin** [comment]
Works great for me. 🎉 
I still want to check 2/3 things here and there and I'll merge.

**Comment by mgechev** [comment]
The global java dependency is the only thing which slightly bothers me, in case it turns out to be the bottleneck we can switch to uglifyjs.

**Comment by mgechev** [comment]
Switched to `gulp-uglify`. Now the gzipped production bundle is 139K!

**Comment by Bigous** [comment]
I'm receiving 15 warnings on minify, as it is already concatenated, I couldn't see where the warnings.

Besides this, it's good to go to me.

**Comment by NathanWalker** [comment]
Amazing. I see the warnings, but works great here too 👍 @mgechev bravo for this incredible work.

**Comment by mgechev** [comment]
@Bigous, @NathanWalker warnings coming from minification with uglify?

**Comment by NathanWalker** [comment]
@mgechev I just cloned fresh, reinstalled and no warnings this time. It works perfectly. (previously did a merge so must have been local only).
LGTM!!!

**Comment by TheDonDope** [comment]
Working fine for me as well! :shipit:

**Comment by Bigous** [comment]
Working on fresh - my bad.

**Comment by mgechev** [comment]
Soo, anyone want to merge? :-)

**Comment by mgechev** [comment]
@ludohenin do you confirm that it's ready to merge?

**Comment by StefanKoenen** [comment]
I've merged the branch in my project, and i've this error; https://xevro.nl/sharex/ConEmu64_2016_09_03_12_41_42_aa65133c-ef18-45d5-b567-aebef73f0ab3.png

**Comment by ludohenin** [comment]
:champagne:

**Pull request merged**
