### PR TITLE
Major Travis CI update

### PR DESCRIPTION
**Pull request by tarlepp**
Added support for both Linux and OSX environments
Added support for 0.12, 4.0, 4.1 and 4.2 node

### CODE REVIEW

**Comment by tarlepp** [comment]
And here you can find results from my forked branch https://travis-ci.org/tarlepp/angular2-seed/builds/87928518

**Comment by tarlepp** [comment]
Although it's weird that this one seems to run also ```0.12``` node without problems as in #196 as you can see:
https://travis-ci.org/tarlepp/angular2-seed/jobs/87928519#L237 (Linux)
https://travis-ci.org/tarlepp/angular2-seed/jobs/87928523#L52 (OSX)

**Comment by tarlepp** [comment]
Hmm, and with this official Travis CI, it seems to fail that as in supposed. https://travis-ci.org/mgechev/angular2-seed/jobs/87934596 and OSX builds are failing because of GitHub rate limit, which is discussed in #176 #184 and #200

**Comment by tarlepp** [comment]
Oh, now I remember that master branch which I used to test this travis CI setup has #196 merged into, so that's why 0.12 node tests are run without any failures.

I made small change to config to not include 0.12 yet. Allthough builds are failing because of that rate limit barrier.

**Comment by tarlepp** [comment]
Seems like OSX builds have some network problems within travis that occurs randomly.

https://travis-ci.org/mgechev/angular2-seed/jobs/87940876#L79

Haven't figured out any solution for this yet. This same occurred within my test builds, and I just re-run all tests (Hit restart test button from Travis) and all build was build ok.

Anyone else have some information about this behaviour?

**Comment by tarlepp** [comment]
Not yet merged?

**Comment by mgechev** [comment]
Looks good! I'll review it later today and merge.

**Comment by tarlepp** [comment]
Damn that version check is messing this one quite bit. Closing for now, until I get this fixed and then making new PR.

**Pull request closed without merging**
