### PR TITLE
feature/enable-scss - issue #895

### PR DESCRIPTION
**Pull request by hank-ehly**
Define stylesheet implementation of choice without manually editing the seed (#895 ).

- Default stylesheet remains css
- Enable scss file processing via `--scss` flag
- Uses [default sass-lint configuration](https://github.com/sasstools/gulp-sass-lint/blob/master/tests/.sass-lint.yml)
- Includes modifications made in [angular2-seed-sass](https://github.com/archfirst/angular2-seed-sass) as well as [Add-Sass-support wiki](https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support)

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@hank-ehly You will need to fix the linting errors as they fail CI

**Comment by kashyapmukkamala** [comment]
+1 for this, much needed feature

**Comment by hank-ehly** [comment]
@d3viant0ne 

Understood. I'll deal with this asap.

**Comment by mgechev** [comment]
@hank-ehly great job! I restarted the AppVeyor build, tomorrow I'll review and merge.

**Comment by Shyam-Chen** [comment]
Put it in the wiki is better (IMO)

**Comment by TheDonDope** [comment]
We should update the Wiki article https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support now that the PR is merged.

**Comment by TheDonDope** [comment]
@hank-ehly what is the other necessary minimum setup necessary to make use of the scss processing? Is renaming the `.css` files to `.scss` files enough? Do we still need to move the `src/client/css/main.css` and rename to `src/client/assets/main.scss` ? Thanks for the info!

**Comment by hank-ehly** [comment]
@TheDonDope 

The minimum requirements to enable SCSS process are:
- Change **all** client/**/*.css files to *.scss
- Set the ENABLE_SCSS config value to `true` during a build or serve task
    1. `npm run build.[env] -- --scss`
    2. set `ENABLE_SCSS` to `true` in either project.config or seed.config  (#954)

**Comment by hank-ehly** [comment]
@TheDonDope

Thank you. I would like to note that setting the flag through project.config is currently **not** working. I apologize for not having researched further, but I believe it may be related to issue #823.

**Comment by TheDonDope** [comment]
@hank-ehly You are welcome. Yes, i updated the wiki article (https://github.com/mgechev/angular2-seed/wiki/Enabling-SASS-support) and included that info. Could you have a quick review it, if i described it correctly? Thank you!

**Comment by hank-ehly** [comment]
@TheDonDope 

I just read the updated wiki page. Everything looks great!
Thank you for your time.

Hank

**Comment by gvsdan** [comment]
this configurations is not working for build.prod is not injecting the NPM dependencies.

**Pull request merged**
