### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by tarlepp**
After this just enable Travis CI service under https://github.com/mgechev/angular2-seed/settings/hooks Basically each new PR / commit will run all tests, so we can be sure that anything is not broken.

Example Travis CI log there https://travis-ci.org/tarlepp/angular2-seed/jobs/84976434

### CODE REVIEW

**Comment by NathanWalker** [comment]
Excellent thanks for this.

**Comment by tarlepp** [comment]
This will also solve #122

**Comment by mgechev** [comment]
Awesome, thanks!

**Comment by tarlepp** [comment]
Remember to activate Travis CI service to this repo, so that tests are run automatic.

**Comment by mgechev** [comment]
Yep, I did.

**Pull request merged**
