### PR TITLE
#688 add --color flag to npm script calls to Gulp

### PR DESCRIPTION
**Pull request by brian428**

### CODE REVIEW

**Comment by mgechev** [comment]
AppVeyor failed on any reason (doesn't seems related to your changes).

**Comment by natarajanmca11** [comment]
I am getting the same error in my machine (MacBookPro with Windows 10 OS). But in OSX, its fine.
Error Message :  Not compatible with your operating system or architecture: fsevents@1.0.9

**Comment by mgechev** [comment]
@brian428 it seems the flag breaks something on Windows :disappointed: 

We can add a FAQ section in the wiki which explains how you can enable coloring with the `--color` flag. Would you add such?

**Comment by brian428** [comment]
OK, I'll add this to the wiki instead. It's just odd, because I'm on Windows and this works fine. Strange.

**Comment by natarajanmca11** [comment]
This issue is not because of `--color`.  
Please refer the issue https://github.com/npm/npm/issues/9204

**Pull request merged**
