### PR TITLE
Added contributing guidelines. Solves #157

### PR DESCRIPTION
**Pull request by tarlepp**

### CODE REVIEW

**Comment by mgechev** [comment]
Would you include information about linting as well?

**Comment by ludohenin** [comment]
Looks good to me.

**Comment by tarlepp** [comment]
Lets update this guide when we have real solution for linting task.

**Comment by mgechev** [comment]
@tarlepp we have already have linting with `gulp tslint`.

**Comment by ludohenin** [comment]
Agree with @mgechev. It's [here](https://github.com/mgechev/angular2-seed/blob/master/gulpfile.ts#L61)

**Comment by tarlepp** [comment]
Ok, so all should be ok now - right?

**Comment by mgechev** [comment]
Looks good to me!

**Comment by ludohenin** [comment]
@tarlepp can you squash and push again ?

**Comment by ludohenin** [comment]
@tarlepp can you squash your commits into one ?

**Comment by tarlepp** [comment]
Damn, my git skills aren't so good - Tried to squashs those three commits to one, but now success. I'll make new clean PR for this later today.

**Pull request closed without merging**
