### PR TITLE
Fixed preinstall task, which was failing with Travis.

### PR DESCRIPTION
**Pull request by tarlepp**

### CODE REVIEW

**Comment by ludohenin** [comment]
Is that a specific Travis behavior ?

**Comment by tarlepp** [comment]
That's propably because npm install tsd will make local installation to clean linux box, so there isn't tsd installed as global.

**Comment by mgechev** [comment]
Thanks for that! May be we can use path.join for getting the correct path?

**Comment by tarlepp** [comment]
Ah, good catch will check that.

**Comment by tarlepp** [comment]
Hmm, seems like this was not fix...

**Comment by mgechev** [comment]
Yeah, there was a problem with the async behavior of the preinstall task. You can find working build here https://github.com/mgechev/angular2-seed/pull/154

We can close this PR?

**Comment by ludohenin** [comment]
@mgechev I think so

**Comment by tarlepp** [comment]
Thanks for that.

**Pull request closed without merging**
