### PR TITLE
View Production build

### PR DESCRIPTION
**Pull request by ishara**
Viewing generated production build.

### CODE REVIEW

**Comment by mgechev** [comment]
@ishara looks good but the build is failing. I believe that is due to missed type annotation for the `done`.

**Comment by ishara** [comment]
Please help me to figure out why build failed, this is work for me.

**Comment by mgechev** [comment]
```
gulpfile.ts (109,19): Parameter 'done' implicitly has an 'any' type. (7006)
```

**Comment by ishara** [comment]
How can I fix Travis CI build error?

**Comment by mgechev** [comment]
We have `noImplicitAny` compiler option. You need to take care of the lack of type annotations in your changes.

Also once you're ready, please squash to a single commit.

**Comment by mgechev** [comment]
@ishara would you add a wiki page where you explain the steps you went through in the process of adding a dev server?

**Pull request closed without merging**
