### PR TITLE
Speeding app start

### LINKED ISSUE #400: loading all angular2 js separated
I broke this issue out of a compounded issue here:
https://github.com/mgechev/angular2-seed/issues/399 ... which I renamed to his other issue.

As @gustavolira mentions...

> Today I did a pull at project and now I all angular2 js is loading separeted taking much more time to finish to load the page. 
> [omitted]
> There's some way to load only angular2 bundle js instead of separeted?

I have also seen this in the latest changes and not sure why every single little .js file is now loading separately. It makes development much slower as the page load to refresh is now painfully slow. :(

### PR DESCRIPTION
**Pull request by mgechev**
Fix #400

### CODE REVIEW

**Comment by NathanWalker** [comment]
Confirmed. Fixed. lgtm, thanks!

I'm not familiar with AppVeyor, but I think there's been an issue there for awhile. Everything else passes.

**Comment by mgechev** [comment]
This caused https://github.com/mgechev/angular2-seed/issues/402

**Comment by Bigous** [comment]
agree!

**Comment by NathanWalker** [comment]
https://github.com/angular/angular/issues/6501

**Comment by NathanWalker** [comment]
Also related, other seeds see same IE problem:
https://github.com/AngularClass/angular2-webpack-starter/issues/213

**Comment by mgechev** [comment]
I thought it wasn't an issue related to the seed but I didn't have time to dig deeper.

@NathanWalker thanks for the link!

**Pull request merged**
