### PR TITLE
Tsconfig simplification: No need to specify all files.

### PR DESCRIPTION
**Pull request by jesperronn**
* [x] Specify outdir so that IDE builds will put generated js there.
      This allows Atom editor's Typescript plugin to work without dropping
      tsconfig.json files and generated .js files in the source directory

* [x] simplify tsconfig.json so that it is NOT updated by an eager
      IDE if files are added/removed

This fixes issue #219 and is following how Angular2 does it.

See also angular2 commit https://github.com/angular/angular/commit/5b104936ae55dc1b5b5ca687a912e703dd50dfa4 by @alexeagle'

### CODE REVIEW

**Comment by ludohenin** [comment]
I don't think we need the outDir to be set. We have a task for compiling ts.

**Comment by jesperronn** [comment]
@ludohenin OK will remove, then

**Comment by ludohenin** [comment]
I'd also keep `compileOnSave` to false.

**Comment by jesperronn** [comment]
@ludohenin I removed it because `compileOnSave` is not in the spec

**Pull request merged**
