### PR TITLE
added the ability to configure a proxy for api calls

### PR DESCRIPTION
**Pull request by menostos**

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@mgechev @ludohenin - I would think this falls into the Example Document in the wiki department.

There are tons of ways to accomplish this, I don't know that I would want to go in any one direction in the core seed project.

**Comment by mgechev** [comment]
Yes, I agree that it'll be great to add it into an example document and keep it out of the seed at this point.

**Comment by mgechev** [comment]
@menostos would you create a wiki page explaining how you can integrate a proxy middleware to browsersync?

**Comment by menostos** [comment]
Added [Wikipage](https://github.com/mgechev/angular2-seed/wiki/Add-a-Proxy-to-browsersync).
Feel free to edit/correct it.

**Comment by mgechev** [comment]
@menostos sounds great to me! I'll update the list of contributors in a day or two to reflect the wiki page you added!

**Pull request closed without merging**
