### PR TITLE
Gulp src reference

### PR DESCRIPTION
**Pull request by aboeglin**
I have extended the Configuration variables and used them to define the PATH. Like this we can just do changes to the paths at one point. So we can now change the source and destination paths easily.

I have also added a folder created by webstorm in the .gitignore.

### CODE REVIEW

**Comment by ludohenin** [comment]
In my opinion, this needs some clean-up.
* intendation: 2 spaces
* use `join(var, 'tesxt')` instead of ` var+'text'` (at least `var + 'text')

**Comment by mgechev** [comment]
Yeah, I agree with @ludohenin. @aboeglin would you fix these two points. Otherwise it is ready to be merged! Thanks for the PR!

**Comment by aboeglin** [comment]
Agreed, my editor indented to 4 spaces, I'll fix it and use join() where appropriate. I'll try to do it tonight.

**Comment by aboeglin** [comment]
Also now that I think about it, I could also update the readme file in the Configuration section to briefly describe it.

**Comment by aboeglin** [comment]
Ok it should be good now !

**Comment by mgechev** [comment]
Looks good to me! Thanks for the PR!

**Pull request merged**
