### PR TITLE
fix: reinstall

### PR DESCRIPTION
**Pull request by Shyam-Chen**

### CODE REVIEW

**Comment by mgechev** [comment]
This is fix for windows?

**Comment by Shyam-Chen** [comment]
I was using windows 10

**Comment by d3viant0ne** [comment]
Interesting, the change that added /* to reinstall was for windows a month ago.

**Comment by d3viant0ne** [comment]
Yeah, that's what I thought. On a base Windows10 vm with only NodeJS & the seed this is a breaking change.

screen shot 2016-03-11 at 8 30 13 am

**Pull request merged**
