### PR TITLE
fix(tools): TS Project Recreated 

### PR DESCRIPTION
**Pull request by brian428**
Regarding #496, the current tsProjectFn is recreating the TS project each time the utility function is called. Changing it to create the project once and then reuse it on subsequent calls (e.g. after a watch change).

### CODE REVIEW

**Comment by mgechev** [comment]
@brian428 great! Would you resolve the merge conflict in order to merge?

**Comment by brian428** [comment]
Will do! I'll look over your recent changes and get this moved to the right spot.

**Comment by brian428** [comment]
Sorry for the merge commit, but the only other option I could think of would have been to revert, pull, re-apply my change, and force push back to my cloned branch. Which I figured was worse. But let me know if you'd rather I go that route. Thanks.

**Comment by mgechev** [comment]
No worries.

**Comment by brian428** [comment]
Cool. Out of curiosity (if you know), should I have been able to clean that up via rebase without needing to do a forced push to my Github repo? I don't have trouble with fairly straightforward rebasing, but once something has already been pushed to remote, my understanding of the options gets murky. (Other than resorting to a forced push).

**Comment by d3viant0ne** [comment]
@brian428  rebase always requires a force push

From your fork/branch

- git remote add upstream git@github.com:mgechev/angualr2-seed.git
- git fetch upstream master
- git rebase upstream/master
- git push -f

**Comment by brian428** [comment]
OK cool, at least I wasn't missing something then. Thanks!

**Pull request merged**
