### PR TITLE
dev, test and e2e builds are now all running under /dist/dev

### PR DESCRIPTION
**Pull request by nareshbhatia**
I went ahead and made changes as discussed in issue #447. This is working extremely smoothly now.

Other changes:
- `gulpfile` is now alphabetized by task
- TMP_DIR has been moved to `/dist/tmp`. This simplifies the `clean`
task immensely - all it has to do is to delete the `dist` directory.

As a side, the only thing that is bothering me is that `build.js.test.ts` relies on `inlineNg2Template` to execute the tests. This is going to pose a problem when I try to introduce Sass. Is there any way to run the tests without inlining (just like the dev build)?

### CODE REVIEW

**Comment by mgechev** [comment]
Lets wait for an answer by @NathanWalker on https://github.com/mgechev/angular2-seed/issues/447 before merging.

**Comment by nareshbhatia** [comment]
Sounds good.

**Comment by NathanWalker** [comment]
lgtm. Thanks @nareshbhatia !

**Comment by NathanWalker** [comment]
@nareshbhatia If you don't mind making one small modification. I added this when doing the e2e testing but it's inconsistent with other task naming:
https://github.com/mgechev/angular2-seed/pull/482/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17

Please rename that task: `e2e.live`  and if you could update the `README` as well to reflect that rename.

Thank you!

**Comment by nareshbhatia** [comment]
@NathanWalker, sorry not clear on the change you want me to make. Rename the task `e2e.live`? Rename it to what?

**Comment by NathanWalker** [comment]
It's `e2e-live` now.... just renamed to `e2e.live` so it follows the convention of others. :+1:

**Comment by nareshbhatia** [comment]
Ah, I see. Done.

**Pull request merged**
