### PR TITLE
Make it compatible with systemjs 0.19.18

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by mgechev** [comment]
@ludohenin @NathanWalker would you review and merge these changes?

**Comment by mgechev** [comment]
Fixes https://github.com/mgechev/angular2-seed/issues/431.

**Comment by Bigous** [comment]
Hi @mgechev do we need to set System.config 2x ?

**Comment by mgechev** [comment]
Ups, nope. We just need to move the config above the injected libs.

**Comment by NathanWalker** [comment]
I was actually unable to test this due to a `typings` issue. Once this PR https://github.com/mgechev/angular2-seed/pull/437 is merged, then we can likely test this change out. `zone` was renamed to `zone.js` on `typings`. And jasmine needed a commit update.

**Comment by NathanWalker** [comment]
@mgechev Now that https://github.com/mgechev/angular2-seed/pull/437 is merged, you might rebase master here ;) I can verify after that!

**Comment by NathanWalker** [comment]
I rebased master into my local checkout of this and all looked good! merging!

**Pull request merged**
