### PR TITLE
fix(coverage): Adds sourcemaps to coverage report

### LINKED ISSUE #560: Test coverage server report does not include source with 0% coverage
Perhaps I'm missing something, but the coverage reports generated by npm test and viewed by running npm run serve.coverage are a bit misleading if there are source files that are not covered by any test. 

When building and maintaining a large application, it's helpful to see not just how much a particular source file is covered by test, but if there is any source that has no coverage at all. 

I attempted adding "includeAllSource: true" in the coverageReporter configuration in karma.conf.js, which produces the report I might expect, but remap-istanbul chokes on the results, complaining that it can't find main.ts in the dist/dev directory. 

Ideas?

### LINKED ISSUE #567: Coverage remap not working (no remapping of js results to .ts files)
Coverage map error: No sourcemaps found

Running `npm run serve.coverage` (after `npm test`) produces the following:

```
[15:29:02] 130 $ npm run serve.coverage

> angular2-seed@0.0.0 serve.coverage /Users/jesper/src/jesperronn-angular2-seed
> remap-istanbul -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage

[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/about/components/about.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/shared/services/name-list.service.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/home/components/home.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/app.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/navbar.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/toolbar.component.js"]

> angular2-seed@0.0.0 gulp /Users/jesper/src/jesperronn-angular2-seed
> gulp "serve.coverage"

[15:29:09] Requiring external module ts-node/register
[15:29:11] Loading task serve.coverage 
[15:29:11] Using gulpfile ~/src/jesperronn-angular2-seed/gulpfile.ts
[15:29:11] Starting 'serve.coverage'...
[15:29:11] Finished 'serve.coverage' after 6.13 ms

```

Lot's of missing sourcemaps. And I see that the remap has actually not occured. As you can see from the screenshot, coverage maps the js files and not the ts files.

code_coverage_report_for_app_components_navbar_component_js

I am running on latest master (commit 6eca776de0b8b30260b384a4dc9da16edcc88fce ). This is apparently unrelated to #560, which is the full sources mapping flag.

### PR DESCRIPTION
**Pull request by d3viant0ne**
**Do Not Merge This**

This is a work in progress. PR open as @NathanWalker is working an issue that is almost certainly related.

Two issues I can find thus far

- [x] Add sourcemaps in build.js.test

- [ ] Fix command line coverage reporting

- [x] Fix error with remap-istanbul ( wrong source path )
requires - gulp-sourcemaps@master & remap-istangul@master
> remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage

resolves #567 
resolves #560

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@mgechev @ludohenin @NathanWalker something we need to make a decision on. 

> Do we want to report coverage on the Typescript, Transpiled JavaScript or a make it a configurable option?

Given what I have read on the web, people are going to be on one side of the fence or the other. There are obviously going to be differences in what it's going to report. It wouldn't be that much work to move remap-istanbul into a gulp task and make the coverage configurable for either .ts or .js

**Comment by NathanWalker** [comment]
@d3viant0ne Thank you so much for all this. That's something I was curious about as well.
IMO, highlighting the typescript would be great. Ultimately you can never go wrong with making it a configurable option if possible :+1:

**Comment by ludohenin** [comment]
I second @NathanWalker. Configuration shouldn't bring to much complexity.

**Comment by mgechev** [comment]
@d3viant0ne great! Configurable and reporting coverage of TypeScript by default sounds like the best option to me as well.

**Comment by d3viant0ne** [comment]
Alright. I'll go the configurable route.

**Pull request closed without merging**
